logging:
  level: INFO
  loggers:
    UnderArmour: DEBUG

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: unused

  # the password
  password: unused

  # the JDBC URL
  url: unused